### ISSUE TITLE
update wezterm toml files to include metadata

### ISSUE THREAD

**Issue by wez** [EdenEast/nightfox.nvim#183]
Please add a metadata section to your wezterm toml files; a block like this:

```toml
[metadata]
name = "Nightfox"
author = "EdenEast"
origin_url = "https://github.com/EdenEast/nightfox.nvim"
```

added to the bottom of each will allow wezterm to reference the scheme using the name `Nightfox` (if that is the case/capitalization you prefer).

In addition, I can then point wezterm's color scheme sync machinery at this repo to have it include your schemes in wezterm's next release, and keep it updated for future releases.

Having the metadata populated means that wezterm can show the author and upstream URL in its scheme browsing section of the docs; see https://wezfurlong.org/wezterm/colorschemes/b/index.html#belafonte-day for an example.

I think that would indirectly satisfy the wezterm users that filed https://github.com/EdenEast/nightfox.nvim/issues/156
